### ISSUE TITLE
How to  ‘construct_graph’ ？

### ISSUE THREAD

**Issue by cxzyoung** [bdy9527/SDCN#13]
感谢您的工作，我在看代码的时候发现在calcu_graph.py中进行construct_graph时需要用到标签数据，请问对于无标签的非graph数据或者无标签的graph数据，应该怎样去构造graph？

**Comment by bdy9527** [comment]
标签数据并没有被用在构造graph中。在calcu_graph.py中，label只出现在了第12行和40行，第12行是为了统计样本数量，第40行是为了统计构造出的图有多少是inter-edge，有多少是intra-edge。所以其实注释掉也是没问题的。

无标签的非graph数据可以注释掉12，40，41行就可以了；无标签的graph数据，因为已经有了graph，就没必要去构造了。

**Comment by cxzyoung** [comment]
感谢老师的回答，非常感谢
