### ISSUE TITLE
Citeseer dataset is missing 

### ISSUE THREAD

**Issue by goodman1204** [bdy9527/SDCN#18]
The attribute of Citeseer is misssing (**cite.txt**) in the data directory. Could you kindly upload it?

**Comment by bdy9527** [comment]
Due to the limitation of file size, the complete data can be found in Baidu Netdisk:

graph: 链接:https://pan.baidu.com/s/1MEWr1KyrtBQndVNy8_y2Lw 密码:opc1

data: 链接:https://pan.baidu.com/s/1kqoWlElbWazJyrTdv1sHNg 密码:1gd4

**Comment by goodman1204** [comment]
Thanks. My fault, I didn't read the readme carefully.
