### ISSUE TITLE
Lack of description about dataset for training

### ISSUE THREAD

**Issue by rose-jinyang** [bdy9527/SDCN#3]
Hello
Thanks for contributing this paper and code.
But I feel the lack of description about dataset structure.
I am going to apply this to face clustering.
Is it possible for 5M face clustering too?
Could u explain it in detail?

**Comment by bdy9527** [comment]
Thanks for the attentions.

In general, if you want to apply our model to other datasets, two steps are required. 
First, constructing the KNN graph based on the similarities of samples. Details can be found in ```calcu_graph.py``` The KNN graph is stored as the form of edges.
Second, pretraining the autoencoder and save the pre-trained model. Details can be found in ```data/pretrain.py``` The pretrain model is stored as the form of pkl.
Finally, replace the args in ```sdcn.py``` and run the code.
Hope this can help you.

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.
I hope that the above description will be added in README.
I have one more question.
Did u review CDP or LTC(GCN-D & GCN-S) methods based on supervised learning for large scale face clustering?
How about comparing SDCN with these methods?
Please let me know asap.
Thanks.

**Comment by bdy9527** [comment]
Thanks for the advice.

Actually, I'm not familiar with large scale face clustering and SDCN does not use supervised information. Therefore, the performance may not meet your expectations.

Besides, a suitable encoder is important for deep clustering. For the sake of generality, we use the basic autoencoder to learn representations for different types of data (i.e., image, text, attributes). If you focus on face clustering, the pre-trained CNNs maybe more helpful.

**Comment by rose-jinyang** [comment]
Thanks for your reply.

**Comment by lucy3589** [comment]
> Hello
> Thanks for contributing this paper and code.
> But I feel the lack of description about dataset structure.
> I am going to apply this to face clustering.
> Is it possible for 5M face clustering too?
> Could u explain it in detail?
this code need set cluster_number?

**Comment by lucy3589** [comment]
> Thanks for the advice.
> 
> Actually, I'm not familiar with large scale face clustering and SDCN does not use supervised information. Therefore, the performance may not meet your expectations.
> 
> Besides, a suitable encoder is important for deep clustering. For the sake of generality, we use the basic autoencoder to learn representations for different types of data (i.e., image, text, attributes). If you focus on face clustering, the pre-trained CNNs maybe more helpful.


this code need set cluster_number?
