### ISSUE TITLE
question about the dataset (ACM)

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [bdy9527/SDCN#5]
Thanks for your great work.
I have a small question about your ACM dataset. I noticed you mentioned in the paper that you "divide the papers into three classes (database, wireless communication, data mining) by their research area". Does that mean the "database" is labelled as 0, "wireless communication" is 1, "data mining" is 2. 

Just wanna better understand the graph and the results. Thx

**Comment by bdy9527** [comment]
The ACM dataset is from https://github.com/Jhy1993/HAN, maybe you can find more details in this paper.

**Comment by zhiqiangzhongddu** [comment]
Thx, I'll contact Houye for more details. 
Cheers.
