### ISSUE TITLE
graph.txt

### ISSUE THREAD

**Issue by lhy2749** [bdy9527/SDCN#7]
what is the different between reut1_graph.txt ,reut3_graph.txt, reut5_graph.txt and reut10_graph.txt?
when i use 'run sdcn.py --name reut' , i found only 'reut3_graph.txt' is used.But in calcu_graph.py,the fname is 'graph/reut10_graph.txt'. if only one graph.txt is used for sdcn.py?

**Comment by bdy9527** [comment]
reut{k}_graph.txt, *k* means the number of the nearest neighbors

**Comment by lhy2749** [comment]
3q
