### ISSUE TITLE
Eq(7)?

### ISSUE THREAD

**Issue by lhy2749** [bdy9527/SDCN#8]
Hi, I can not find where is Eq(7) in your codes.
![image](https://user-images.githubusercontent.com/43692386/82830084-5fcb1480-9ee7-11ea-8c6e-16ac3d1d69b0.png)

**Comment by kouyongqi** [comment]
His code may not mention it, and make it set z(l+1) = z(l) + h(l), I'm not find 0.5,it is mention in paper

**Comment by bdy9527** [comment]
Thank you for reminding, we have fixed the bug.
