### ISSUE TITLE
batch_size

### ISSUE THREAD

**Issue by Sweetii-huan** [bdy9527/SDCN#9]
Thanks for your great work, but I have some questions about the training batch size. 
Must data be entered all at once?
Can't we have batch_size?
If we have batchsize, what do we do with the adjacency matrix?

**Comment by bdy9527** [comment]
Because GCN is trained with full-batch, so SDCN is also full-batch. If you want to use mini-batch, you can try the sampling-based GNNs, e.g., GraphSAGE.
